import pandas as pd

In [5]:
import pandas as pd

In [5]:
sales = pd.read_csv("salesdata.csv")

In [10]:
sales.head()

,OrderID,OrderDate,Region,CustomerType,Category,Product,Quantity,UnitPrice,Discount,Returned
0,1001,2024-01-05,East,Corporate,Technology,Wireless Mouse,4.0,25.5,0.0,No
1,1002,2024-01-06,West,Consumer,Office Supplies,Mechanical Pencil Set,10.0,8.0,0.1,No
2,1003,2024-01-07,Central,Home Office,Furniture,Ergonomic Chair,1.0,250.0,0.05,No
3,1004,2024-01-08,South,Consumer,Technology,Bluetooth Speaker,2.0,45.0,0.0,Yes
4,1005,2024-01-09,East,Corporate,Office Supplies,Gel Pens 12-Pack,5.0,12.0,0.0,No

In [11]:
sales.tail()

,OrderID,OrderDate,Region,CustomerType,Category,Product,Quantity,UnitPrice,Discount,Returned
120,1118,2024-05-01,East,Corporate,Technology,Wireless Mouse,4.0,$25.50,0%,No
121,1119,2024-05-02,West,Consumer,Office Supplies,Gel Pens 12-Pack,10.0,$12.00,10%,No
122,1120,2024-05-03,Central,Home Office,Furniture,Ergonomic Chair,1.0,$250.00,5%,Yes
123,1121,2024-05-04,South,Corporate,Technology,USB-C Hub,3.0,$35.00,0%,No
124,1122,2024-05-05,East,Consumer,Office Supplies,Sticky Notes Pack,15.0,$3.20,0%,No

In [7]:
sr1 = pd.Series([1, 2, 3, 4, 5])

In [8]:
sr1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
sr1.shape

(5,)

In [10]:
sr2 = pd.Series([2.5, 3.5, 4.5, 5.5])

In [11]:
sr2

0    2.5
1    3.5
2    4.5
3    5.5
dtype: float64

In [12]:
sr3 = pd.Series([2.5, 3.5, 4.5, 'a'])

In [13]:
sr3

0    2.5
1    3.5
2    4.5
3      a
dtype: object

In [16]:
sr4 = pd.Series(('a','b','c','d','e'))

In [15]:
sr4

0    a
1    b
2    c
3    d
4    e
dtype: object

In [17]:
sr4

0    a
1    b
2    c
3    d
4    e
dtype: object

In [21]:
sr5 = pd.Series([100, 101, 102, 103], index=['a', 'b', 'c', 'd'], name= 'roll_no')

In [20]:
sr5

a    100
b    101
c    102
d    103
dtype: int64

In [22]:
sr5

a    100
b    101
c    102
d    103
Name: roll_no, dtype: int64

In [28]:
sr5.iloc[0]

np.int64(100)

In [30]:
sr5.loc['a']

np.int64(100)

In [32]:
df1 = pd.DataFrame({'srno':[1,2,3,4,5], 'name':['yash','Ankit','anurag','vivek','vansh']})

In [33]:
df1

   srno    name
0     1    yash
1     2   Ankit
2     3  anurag
3     4   vivek
4     5   vansh

In [34]:
df1.ndim

2

In [35]:
df1.dtypes

srno     int64
name    object
dtype: object

In [36]:
df1.shape

(5, 2)

In [38]:
df1 = pd.DataFrame({'srno':[1,2,3,4,5], 'name':['yash','Ankit','anurag','vivek','vansh']}, index=[1,2,3,4,5])

In [39]:
df1

   srno    name
1     1    yash
2     2   Ankit
3     3  anurag
4     4   vivek
5     5   vansh

In [46]:
df1.iloc[0,1]

'yash'

In [48]:
df1.loc[5, 'name']

'vansh'

In [49]:
df1.iloc[0:3]

   srno    name
1     1    yash
2     2   Ankit
3     3  anurag

In [51]:
df1.loc[1:3, 'name']

1      yash
2     Ankit
3    anurag
Name: name, dtype: object

In [53]:
df1.loc[1:3, 'srno']

1    1
2    2
3    3
Name: srno, dtype: int64

In [54]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 1 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   srno    5 non-null      int64
 1   name    5 non-null      object
dtypes: int64(1), object(1)
memory usage: 292.0+ bytes

In [55]:
import pandas as pd

sales = pd.read_csv("salesdata.csv")

In [58]:
sales.head()

,OrderID,OrderDate,Region,CustomerType,Category,Product,Quantity,UnitPrice,Discount,Returned
0,1001,2024-01-05,East,Corporate,Technology,Wireless Mouse,4.0,25.5,0.0,No
1,1002,2024-01-06,West,Consumer,Office Supplies,Mechanical Pencil Set,10.0,8.0,0.1,No
2,1003,2024-01-07,Central,Home Office,Furniture,Ergonomic Chair,1.0,250.0,0.05,No
3,1004,2024-01-08,South,Consumer,Technology,Bluetooth Speaker,2.0,45.0,0.0,Yes
4,1005,2024-01-09,East,Corporate,Office Supplies,Gel Pens 12-Pack,5.0,12.0,0.0,No

In [61]:
sales.tail()

,OrderID,OrderDate,Region,CustomerType,Category,Product,Quantity,UnitPrice,Discount,Returned
120,1118,2024-05-01,East,Corporate,Technology,Wireless Mouse,4.0,$25.50,0%,No
121,1119,2024-05-02,West,Consumer,Office Supplies,Gel Pens 12-Pack,10.0,$12.00,10%,No
122,1120,2024-05-03,Central,Home Office,Furniture,Ergonomic Chair,1.0,$250.00,5%,Yes
123,1121,2024-05-04,South,Corporate,Technology,USB-C Hub,3.0,$35.00,0%,No
124,1122,2024-05-05,East,Consumer,Office Supplies,Sticky Notes Pack,15.0,$3.20,0%,No

In [63]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       125 non-null    int64
 1   OrderDate     125 non-null    object
 2   Region        124 non-null    object
 3   CustomerType  124 non-null    object
 4   Category      124 non-null    object
 5   Product       124 non-null    object
 6   Quantity      124 non-null    float64
 7   UnitPrice     124 non-null    object
 8   Discount      124 non-null    object
 9   Returned      124 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 9.9+ KB

In [67]:
sales['OrderDate'] = pd.to_datetime(sales['OrderDate'], format= 'mixed', errors= 'coerce')

In [69]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       125 non-null    int64
 1   OrderDate     125 non-null    datetime64[ns]
 2   Region        124 non-null    object
 3   CustomerType  124 non-null    object
 4   Category      124 non-null    object
 5   Product       124 non-null    object
 6   Quantity      124 non-null    float64
 7   UnitPrice     124 non-null    object
 8   Discount      124 non-null    object
 9   Returned      124 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(7)
memory usage: 9.9+ KB

In [71]:
sales['UnitPrice'].unique()

array(['25.5', '8.0', '250.0', '45.0', '12.0', '450.0', '35.0', '5.5',
       '320.0', '28.0', '18.5', '60.0', '110.0', '6.5', '199.99', '650.0',
       '3.2', '180.0', '7.5', nan, '-450.0', '99999.0', '$25.50',
       '$12.00', '$250.00', '$35.00', '$3.20'], dtype=object)

In [74]:
sales['UnitPrice'] = sales['UnitPrice'].astype (str).replace('$','',regex=False)
sales['UnitPrice'] = pd.to_numeric(sales['UnitPrice'], errors='coerce')

In [75]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       125 non-null    int64
 1   OrderDate     125 non-null    datetime64[ns]
 2   Region        124 non-null    object
 3   CustomerType  124 non-null    object
 4   Category      124 non-null    object
 5   Product       124 non-null    object
 6   Quantity      124 non-null    float64
 7   UnitPrice     119 non-null    float64
 8   Discount      124 non-null    object
 9   Returned      124 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 9.9+ KB

In [76]:
sales['Discount'] = sales['Discount'].astype (str).replace('%','',regex=False)
sales['Discount'] = pd.to_numeric(sales['Discount'], errors='coerce')

In [77]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       125 non-null    int64
 1   OrderDate     125 non-null    datetime64[ns]
 2   Region        124 non-null    object
 3   CustomerType  124 non-null    object
 4   Category      124 non-null    object
 5   Product       124 non-null    object
 6   Quantity      124 non-null    float64
 7   UnitPrice     119 non-null    float64
 8   Discount      119 non-null    float64
 9   Returned      124 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 9.9+ KB